### ISSUE TITLE
Private API key

### ISSUE THREAD

**Issue by bitseater** [Dirli/pantheon-meteo#1]
Hi, you must stop to use my API key. It isn't included in GPL3 license. You must create your own account at [OWM Sign Up](https://home.openweathermap.org/users/sign_up).

Otherwise, my code is licensing under GPL3, so you can use under the same license. Take a look to [GNU GPL v.3](https://www.gnu.org/licenses/gpl-3.0.html)

**Comment by Dirli** [comment]
Your key
API_KEY = "936b1aed9a541e3446cafb8be2c70e62";
My key
API_KEY = "5767c553547943d85f70c2849aa47cc8";

**Comment by bitseater** [comment]
Thanks Dirli.
